### ISSUE TITLE
Enable OCSP Stapling

### ISSUE THREAD

**Issue by dasJ** [stuvusIT/reverse_proxy#12]
See [this generated code](https://mozilla.github.io/server-side-tls/ssl-config-generator/) for Infos about OCSP stapling.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 231 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 238 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 281 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 300 days.

**Comment by Scriptkiddi** [comment]
this is already fixed
