### ISSUE TITLE
302 redirect is not correct l

### ISSUE THREAD

**Issue by Scriptkiddi** [stuvusIT/reverse_proxy#17]

**Comment by Mr-Pi** [comment]
Indeed, for known domains it has to be a 301 and for yet unknown domains 302

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 198 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 206 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 249 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 268 days.

**Comment by Mr-Pi** [comment]
See #42 .
