### ISSUE TITLE
Allow running  hooks on the target machines to reload services

### ISSUE THREAD

**Issue by dasJ** [stuvusIT/reverse_proxy#35]

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 18 days.

**Comment by Mr-Pi** [comment]
Can you be a bit more specific? You mean some commands to execute on the target machines? Or a list on services to restart on them?

**Comment by dasJ** [comment]
Commands. Like `systemctl reload nginx` or `systemctl restart exim4` or `chmod 777 /etc/ssl/privkey.pem`

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 203 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 369 days.
