### ISSUE TITLE
Move letsencrypt to own role for reusability

### ISSUE THREAD

**Issue by dasJ** [stuvusIT/reverse_proxy#5]

**Comment by dasJ** [comment]
Why

**Comment by Mr-Pi** [comment]
LetsEncrypt/certbot und nginx sind in dieser role zu stark ineinander verschmolzen. LetsEncrypt braucht nginx um die certs zu beziehen(nginx.conf). Nginx ist so ausgelegt, das es entsprechend der LetsEncrypt Anfragen mit der Webseite(als reverse Proxy) oder mit dem WebRoot für LetsEncrypt reagiert.

**Comment by Mr-Pi** [comment]
Solltest du da eine saubere Lösung sehen, lass es mich gerne wissen, ich sehe da grade keine Gute Möglichkeit das zu trennen.
