### ISSUE TITLE
Allow to define proxy target port

### ISSUE THREAD

**Issue by Mr-Pi** [stuvusIT/reverse_proxy#54]

**Comment by haslersn** [comment]
Isn't that already possible via

```
    locations:
      - condition: /
        content: proxy_pass http://localhost:12345
```

where `12345` is an arbitrary target port?

**Comment by dasJ** [comment]
This is [already implemented](https://github.com/stuvusIT/reverse_proxy/blob/master/templates/reverse_proxy.conf.j2#L65)

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 141 days.
