### ISSUE TITLE
cert pinning

### ISSUE THREAD

**Issue by Scriptkiddi** [stuvusIT/reverse_proxy#7]

**Comment by dasJ** [comment]
HPKP ist nicht sehr schön mit LE, außerdem hat man recht wenig Mehrwert sicherheitstechnisch, dafür eine hohe Gefahr, sein HTTPS kaputt zu machen.

**Comment by Scriptkiddi** [comment]
naja wir würden die angriffs fläche halt schließen das irgendeine shitty ca ausversehen certs für uns austellt

**Comment by Scriptkiddi** [comment]
warum ist das deiner meinung nach für letsencrypt nicht schön pinnste das ganze halt auf letsencrypt und 4 weitere cas

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 229 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 236 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 279 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 298 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 406 days.
